server:
  port : 7070

spring:
  application:
    name: study-shop

---
spring:
  datasource:
    url: ${LOCAL_DB_URL_MYSQL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: mysql

---


