server:
  port : 7070

spring:
  main:
    allow-circular-references: true
  application:
    name: study_shop
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate:
      sql: debug
      orm.jdbc.bind: TRACE
